### ISSUE TITLE
Download delay

### ISSUE THREAD

**Issue by FGallenkamp** [clemfromspace/scrapy-puppeteer#1]
hey, thanks for this inital attempt,

working good so far, except that the scrapy DOWNLOAD_DELAY setting isn't respected. Any ideas why?

Thanks in advance!

**Comment by FGallenkamp** [comment]
Looked into the scrapy code and found out, that sending a response in DownloaderMiddleware stops the Downloader from further processing, which results in not respecting the download delay.. I will upload a version which can cope with it, but it requires to write some adapted Downloader.

**Comment by thernstig** [comment]
@faeit Is the fix here or will it be in the scrapy codebase?

**Comment by faeit** [comment]
Ideally there would be an alternative downloader in the scrapy codebase or in a plugin which reuses the related code, but since the scrapy downloader is somehow interweave with the twisted web-protocol downloaders, I think this requires some larger rewrites. At the moment I implemented the delay via a DownloaderMiddleware and some semaphores, but that is more a bypass than a permanent solution. I will publish this soon, but with selenium instead of pyppeteer since there is few development in pyppeteer and selenium webdriver will also communicate with devtools bidirectional in the future.
